baseURL = "https://C0smic01.github.io/"
languageCode = "vi"
title = "C0smic's Blog"
theme = "m10c"
[params]
    avatar = "Entei_29.png"
    author = "C0smic"
    description = "Grand Army of the Republic"

    [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/C0smic01"
    [[params.social]]
        icon = "facebook"
        name = "Facebook"
        url = "https://web.facebook.com/C0smic01/"
    [[params.social]]
        icon = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/tungvo0212/"

    [params.style]
        darkestColor = "#2A2438"
        darkColor = "#352F44"
        lightColor = "#f5e3e0"
        lightestColor = "#f5f5f5"
        primaryColor = "#ffffff"

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

