baseURL = 'https://C0smic01.github.io/'
languageCode = 'vi'
title = 'To the pioneers of 921st Fighter Regiment'
theme = 'm10c'
[params]
    avatar = 'Entei_29.png'
    author = 'C0smic'
    description = 'Grand Army of the Republic'